-- Seed de referencia sem dados ficticios.
-- O backend cria apenas usuarios iniciais quando a tabela de usuarios esta vazia.
-- Produtos, lotes, vendas, combos, eventos e inventarios devem ser cadastrados com dados reais pela aplicacao.
